version: "3.9"
services:
  mysql:
    build:
      context: ./mula-store
      dockerfile: Dockerfile
    env_file:
      - ./mula-store/.env
  api:
    build:
      context: ./mula
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql