version: "3.9"
services:
  frontend:
    build:
      context: ./mula-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80/tcp"
    depends_on:
      - api
  api:
    build:
      context: ./mula
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
  mysql:
    build:
      context: ./mula-store
      dockerfile: Dockerfile
    env_file:
      - ./mula-store/.env